### ISSUE TITLE
'Lottie/Lottie.h' file not found on release builds

### ISSUE THREAD

**Issue by dejakob** [react-native-community/lottie-react-native#177] opened 2017-08-21 16:10 UTC
Dear,

I added lottie-react-native into my project, linked everything and added the framework in build phases. It works well when debugging the project, but when I try to create an archive, it crashes and says `'Lottie/Lottie.h' file not found` in LRNAnimationViewManager.

I'm using "lottie-react-native": "^2.2.0" according to package.json.
How do I fix this issue? This is what my build phases looks like: http://prntscr.com/gb97op

**Comment by jp928** [comment] 2017-08-24 23:35
try

```shell
react-native link lottie-ios
```

**Comment by dejakob** [comment] 2017-08-24 23:41
Yeah I did that, I followed all steps of the guide. I got the project working on the iOS simulator, but it gave an error when building an archive (to go to the app store).

**Comment by jp928** [comment] 2017-08-25 04:14
From schema, did you uncheck parallalize build?
<img width="901" alt="screen shot 2017-08-25 at 2 13 50 pm" src="https://user-images.githubusercontent.com/659612/29699392-acc90a36-899f-11e7-98d6-acab7939424c.png">

**Comment by jp928** [comment] 2017-08-25 04:37
@dejakob 
I modified my header search path as below and it achieved fine.
<img width="798" alt="screen shot 2017-08-25 at 2 36 43 pm" src="https://user-images.githubusercontent.com/659612/29699823-eab5e460-89a2-11e7-8108-d8dbef66bcc3.png">

**Comment by sospedra** [comment] 2017-08-30 10:57
We found out that `lottie` doesn't play well with node 8
We tried with Boron (6.11.2) and it worked wonderful

Is it your case @dejakob ?

**Comment by daywong1119** [comment] 2017-09-07 04:02
Go to `General > Embedded Binaries > add Lottie.framework`

**Comment by fossage** [comment] 2017-10-27 19:04
Just to tack onto what @daywong1119 said, I actually already had Lottie.framework in my embedded binaries but I had just upgraded my version of Lottie, so I had to remove the existing version of Lottie.framework and then re-add it.

**Comment by felixaa** [comment] 2017-11-02 19:56
Where is Lottie.framework located? Can't seem to find it. I installed with pods.

**Comment by fossage** [comment] 2017-11-03 16:28
@felixaa , I think you will want to initially install it using yarn, i.e: 
`yarn add lottie-react-native@2.2.7`

Then in your podfile you can add the following:
```bash
pod 'lottie-ios', :path => '../node_modules/lottie-ios'
pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
```

**Comment by bdanis** [comment] 2017-11-14 20:02
having tremendous issues with this. I have 
• cleaned out my derivedData,
•  and node modules folder, 
• reinstalled everything with NPM.
• opened xcode, 
• embedded the framework (there are two in the list, and they are not always present)
• building succeeds randomly and archive files systematically, 

what am I missing?

**Comment by gpeal** [comment] 2017-12-14 21:34
I don't think there is anything actionable left in this issue. Please reopen if there is.

**Comment by padupuy** [comment] 2018-03-21 11:35
Still a problem when releasing the app.
I had to add `LottieLibraryIOS` to Build Phases > Target Dependencies

And i do **NOT** add `Lottie.framework` to General > Embedded Binaries or General > Linked Frameworks and Libraries

![capture d ecran 2018-03-21 a 12 31 13](https://user-images.githubusercontent.com/715255/37707644-25d1d87e-2d04-11e8-9bba-ad18df0a3a1b.png)

![capture d ecran 2018-03-21 a 12 34 18](https://user-images.githubusercontent.com/715255/37707694-56789d78-2d04-11e8-9b08-d462fddb5053.png)

**Comment by kerihenare** [comment] 2018-03-22 00:03
@padupuy That worked perfectly for me. Thanks heaps!

**Comment by ducpt2** [comment] 2018-04-11 10:25
+1 can not build release.
@padupuy solution doesn't work for me.

**Comment by MrNagoo** [comment] 2018-04-16 16:50
I followed @padupuy and also had the embedded binaries.

**Comment by krunalray** [comment] 2018-07-02 04:02
thanks @padupuy it's work for me

**Comment by tobiaskusnaman** [comment] 2018-08-01 07:04
it works man! Thanks @padupuy

**Comment by quangbachit** [comment] 2018-08-22 19:12
thanks @padupuy it's work for me =)))

**Comment by benjarwar** [comment] 2018-11-15 02:57
@padupuy's solution is the only thing that has worked for me locally and on our CI. Other suggestions, including the docs, caused either crashes in the Simulator or export failures when compiling for the App Store.

We're using Fastlane to code sign and distribute our project, and we received errors like this when adding `Lottie.framework` to "Embedded Binaries":

```
error: exportArchive: Lottie.framework does not support provisioning profiles.

Error Domain=IDEProvisioningErrorDomain Code=10 "Lottie.framework does not support provisioning profiles." UserInfo={NSLocalizedDescription=Lottie.framework does not support provisioning profiles., NSLocalizedRecoverySuggestion=Lottie.framework does not support provisioning profiles, but provisioning profile match AppStore <redacted> has been manually specified. Remove this item from the "provisioningProfiles" dictionary in your Export Options property list.}
```

@emilioicai it seems like the installation instructions are incorrect. Using `react-native link` simply does not work. As a side note, when using `react-native link`, the `.a` and `.framework` files were dropped into "Recovered References" instead of mapping to expected files in "Libraries". Manually linking, skipping adding to "Embedded Binaries", and adding to "Target Dependencies" seems to be the only way to get things work with our configuration:

- Lottie React Native 2.5.10
- Lottie iOS 2.5.0
- Xcode 9.4.1
- React Native 0.57.4
- Fastlane 2.105.2
- NPM 6.4.1
- Node 8.9.4

**Comment by emilioicai** [comment] 2018-11-15 08:11
@benjarwar thanks for the heads up. I'm reopening this issue as it looks like more people are seeing it. The ideal solution would be having `react-native link` working.

**Comment by Siddharth-dubey** [comment] 2018-11-28 11:01
Tried all solutions mentioned here. But now app just keeps on crashing. Had to remove it from project. Hope to see this taken care of during build phase in next release. @emilioicai

**Comment by henrymoulton** [comment] 2019-02-21 15:31
Followed @benjarwar instructions and looks like its rendering, will follow up when we try and build for App Store.

**Comment by henrymoulton** [comment] 2019-02-21 15:32
Followed @benjarwar instructions and looks like its rendering, will follow up when building for App Store.

**Comment by osterbergmarcus** [comment] 2019-03-15 18:26
Had problems with manually linking on iOS.

Working solution:
Add Lottie.xcodeproj & LottieReactNative.xcodeproj to lib/frameworks folder in Xcode
Add Lottie.xcodeproj > Products > Lottie.framework &  LottieReactNative.xcodeproj > Products > libLottieReactNative.a to your targets `Linked Frameworks and Libraries`

Voila!

**Comment by jgreen210** [comment] 2019-03-21 16:20
I just got this error since we'd forgotten to run "react-native link lottie-ios" (but had run "react-native link lottie-react-native"). That meant that were using the latest version of lottie-ios from the cocoapods registry, not the ^2.5.0 that's specified in the lottie-react-native package.json. The latest lottie-ios version in cocoapods registry is currently 3.0.0, which requires swift to be configured. That apparently means that you get this missing header error. I therefore solved this by running "react-native link lottie-ios", saving making swift libraries work for another day.

**Comment by jgreen210** [comment] 2019-03-21 16:25
While investigating the problem I describe in my above comment, I also noticed that the npm registry only has 2.5.0 and 3.0.0 versions of lottie-ios, even though there are also 2.5.1, 2.5.2 and 2.5.3 in the lottie-ios github repo. That means that people that (correctly) use "react-native link lottie-ios" aren't using the latest objective C version of lottie-ios, despite lottie-react-native's ^2.5.0 semver version declaration for lottie-ios.

**Comment by evanjmg** [comment] 2019-04-05 10:04
If you are using pods, remove it from your library and link libraries (make sure it's not there) and make sure it's in your target in the Podfile then pod install and rebuild.

**Comment by orhanoksuzz** [comment] 2019-05-10 22:09
> Still a problem when releasing the app.
> I had to add `LottieLibraryIOS` to Build Phases > Target Dependencies
> 
> And i do **NOT** add `Lottie.framework` to General > Embedded Binaries or General > Linked Frameworks and Libraries
> 
> ![capture d ecran 2018-03-21 a 12 31 13](https://user-images.githubusercontent.com/715255/37707644-25d1d87e-2d04-11e8-9bba-ad18df0a3a1b.png)
> 
> ![capture d ecran 2018-03-21 a 12 34 18](https://user-images.githubusercontent.com/715255/37707694-56789d78-2d04-11e8-9b08-d462fddb5053.png)

thanks bro

**Comment by sinhpn92** [comment] 2019-05-13 02:36
> Just to tack onto what @daywong1119 said, I actually already had Lottie.framework in my embedded binaries but I had just upgraded my version of Lottie, so I had to remove the existing version of Lottie.framework and then re-add it.

Where is `Lottie.framework` located? I Can't find it. I installed my project with pods.

**Comment by lfoliveir4** [comment] 2019-05-18 06:27
It`s Work for me 

#import "Lottie/Lottie.h"


![Captura de Tela 2019-05-18 às 03 27 26](https://user-images.githubusercontent.com/32423942/57965608-e2a4b100-791c-11e9-8af1-6f0399d77b61.png)

**Comment by jwebcat** [comment] 2019-05-24 00:21
@sinhpn92 you have to make sure that you first add the the `Lottie.xcodeproj` from `node_modules` to your Libraries in Xcode. Then make sure that the two files `libLottie.a` and `libLottieReactNative.a` are under "Linked Frameworks and Libraries". After that you can click on the plus in "Embedded Binaries"  and it should show up under `Lottie.xcode.proj>Lottie.frameworkIOS`.

The automatic link steps didn't work for me so I had to do the above. Good Luck!

**Comment by halaszbalazs** [comment] 2019-07-26 09:08
Having the same issue as well, fresh install, linked correctly using react-native link (no cocoapods), Embedded Binaries are in their place. No success, always having header file missing build error. Downgraded to older versions, cleared build folders million times, still no luck. Tried the other solutions mentioned here, no luck. Hopefully a newer release will help this issue get fixed...

**Comment by iamcxa** [comment] 2019-07-28 08:35
@halaszbalazs not sure if you have already solved this issue yet, I may have an answer for you, the point is:

> If you are using react-native <=`0.58` and `lottie-react-natiev@2.6.1`,  please use `lottie-ios@2.5.3`.

I am using Lottie in two react-native projects. One using 0.59.10 and integrated my own BLE native module written by Swift5 for supporting IoT devices which is completely no problem during installation(I integrated a dummy swift file in case to make Swift support); another one stack at version 0.55.3 and not having any Swift things, this one cost me 2 days to integrate Lottie and I had no see any works solution during stockoverflow or github or somewhere yet.

I think the main reason is caused by not built-in correct Swift support in older version react-native, so when people using `lottie-ios` > 3.0.0(which is written by Swift), the error shows.

so if someone using `lottie-ios@2.5.3` and the error goes,  maybe @emilioicai should update the readme file to mention about this.

**Comment by halaszbalazs** [comment] 2019-07-30 07:22
Huge thanks @iamcxa your solution worked perfectly!

**Comment by emilioicai** [comment] 2019-07-30 07:34
Hey @iamcxa , thanks a lot! I'm updating the documentation accordingly and closing this issue

**Closed by emilioicai** 2019-07-30 07:34 UTC
Labels: build issue
