### ISSUE TITLE
FPS Drop on Animation Start - Low Performance

### ISSUE THREAD

**Issue by brandtnewww** [react-native-community/lottie-react-native#582] opened 2019-10-21 21:41 UTC
### Description

When I use specific Lottie Animations, I received from our Motion Designer, the frames per second drop below 30 fps on iOS.

### Steps to Reproduce

1. Download the following Lottie animation as an example:
https://www.dropbox.com/s/a0et4mzruswzdor/RightAnswer1Mobile.json?dl=0

2. Integrate it into your project like this

`<LottieView source={require('../assets/lottie/RightAnswer1Mobile.json')} />`

3. Show Perf Monitor in iOS via Ctrl + Cmd + Z on a simulator or shaking your device.

4. Navigate to a screen with 

**Expected behavior:** Lottie Animation shouldn't drop the frame rate in the UI Thread

**Actual behavior:** Lottie Animation drops the frame rate below 30 fps.

**Addition Info:** I worked with this behavior in Expo SDK 34, SDK 35 with React Navigation 3, then with an ejected Expo App on React Navigation 4 and 5. 

### Versions

 "react-native": "0.61.2",
"lottie-ios": "3.1.3",
"lottie-react-native": "^3.2.1"

**Comment by ayouidaniel** [comment] 2019-12-02 20:59
+1

**Comment by sirajalam049** [comment] 2019-12-10 13:03
+2

**Comment by akshgods** [comment] 2019-12-30 07:29
+3

**Comment by djendacott** [comment] 2020-01-16 04:41
+4

**Comment by epurban** [comment] 2020-01-16 06:21
+5

**Comment by Brianop** [comment] 2020-02-12 00:11
+6

**Comment by brandtnewww** [comment] 2020-02-12 22:24
In the meantime, we switched to https://github.com/MiLeung/rn-sprite-sheet for iOS. This issue did cost us a lot of time & money 😞

**Comment by blackbing** [comment] 2020-02-26 12:19
+7

**Comment by Agby** [comment] 2020-02-27 06:07
+8

**Comment by emilioicai** [comment] 2020-02-27 08:46
@brandtnewww you mentioned it happens only on specific animations, does this mean there are other animations which are working fine? It's possible that your motion designer used a specific feature in After Effects which results in the frame rate drop.

I would need some help to spot this feature in order to have it fixed, could you work with your designer to help me out?

**Comment by brandtnewww** [comment] 2020-03-01 21:19
Hi @emilioicai, thanks for reaching out. I did this project for a client and will ask them to help you with this. I tried to use a few files from https://lottiefiles.com/ which worked fine. Only the files from my client lead to the FPS drop. Hope to come back to you within the next 24 hours.

**Comment by jespejoh** [comment] 2020-03-02 11:41
Hey @emilioicai, thanks for answering! We could put you directly in touch with the designer in our team; probably that would be the fastest thing. Should we just shoot you an email to your Gmail account with a brief introduction? Then you can probably ask for whatever you need for proper debugging :)

**Comment by blackbing** [comment] 2020-03-02 12:17
Hi, we find out the problem is `LinearGradient` in our case. It is perfect if the animation doesn't use `LinearGradient`. We are trying to use react-native Animated to implement animation. But still looking forward to this issue would be resolved. Hope this information is useful.

**Comment by emilioicai** [comment] 2020-03-03 08:30
@blackbing I guess we have a suspect, `LinearGradient` can indeed be an issue. @jespejoh @brandtnewww  could you check with your designers?

**Comment by jespejoh** [comment] 2020-03-03 15:23
@emilioicai Indeed this might be a suspect. We just talked to our designer and he said there are not too many animations that include LinearGradients; however we're going to test performance with the same animation w/ and w/o LinearGradient, maybe that brings some light to the issue...

**Comment by jespejoh** [comment] 2020-03-03 15:40
First tests suggest that this was indeed the issue: we have tested a couple of the same animations w/ & w/o LinearGradient, and once we remove the wrapper with the gradient, it works flawless.

**Comment by brandtnewww** [comment] 2020-03-03 15:42
@blackbing Thanks for coming up with the suggestion to get rid of it! 😊This was quite a nightmare 😅We'll keep you updated if we notice issues with other files.

**Comment by Agby** [comment] 2020-05-21 04:12
Is there any update on this issue?

**Comment by emilioicai** [comment] 2020-07-22 11:13
It looks like LinearGradient was the problem. We also updated versions so performance should be better now. Closing unless someone reports this issue again.

**Closed by emilioicai** 2020-07-22 11:13 UTC

**Comment by Dylan0916** [comment] 2020-08-25 08:22
it doesn't work for me😕
[json](https://drive.google.com/file/d/1IKrlmPnFnV6mOmOx3Ixhf79o5vGgR4MO/view?usp=sharing)

lottie-ios:3.1.8
lottie-react-native: 3.5.0
react-native: 0.60.6
device: i6

**Comment by zyestin** [comment] 2021-01-26 09:53
> ottie-ios

+1

**Comment by zyestin** [comment] 2021-01-26 09:53
> it doesn't work for me😕
> [json](https://drive.google.com/file/d/1IKrlmPnFnV6mOmOx3Ixhf79o5vGgR4MO/view?usp=sharing)
> 
> lottie-ios:3.1.8
> lottie-react-native: 3.5.0
> react-native: 0.60.6
> device: i6

+1

**Comment by phamthang03** [comment] 2023-09-18 04:31
+1
lottie-ios:3.4.0
lottie-react-native: 5.1.6
react-native: 0.72.3
device: iPhone SE 3
