### ISSUE TITLE
Upgrade lottie-android to 2.8.0 - Invalid Layer Save Flag Issue

### ISSUE THREAD

**Issue by 7ynk3r** [react-native-community/lottie-react-native#406] opened 2018-11-09 23:13 UTC
### Description

I'm experiencing this issue
https://github.com/airbnb/lottie-android/issues/802

Looks like we're using 2.5.5
https://github.com/react-community/lottie-react-native/blob/d9f1c88c02c7a38cc81d18009585c07942f387b4/src/android/build.gradle#L30

Which has the following line that causes some issues with newer versions of Android
https://github.com/airbnb/lottie-android/blob/95f07d18ba24b36c114ecdc1d7274971ad490172/lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java#L367

### Steps to Reproduce

Follow the step in the associated ticket.

**Expected behavior:**

The animation should work

**Actual behavior:**

The animation causes the app to crash

### Versions

2.5.*

You can get this information from executing `npm version`.

**Comment by emilioicai** [comment] 2018-11-12 08:45
I guess the solution is to migrate to `lottie-android` 2.7.0. Did you try manually changing that version in gradle?

**Comment by 7ynk3r** [comment] 2018-11-12 21:32
I haven't try yet. I'll see if I have time tonight.

**Comment by ahetawal-p** [comment] 2018-11-20 23:08
@emilioicai I tried changing to `implementation 'com.airbnb.android:lottie:2.7.0'` But seeing this now. 

![screen shot 2018-11-20 at 3 07 21 pm](https://user-images.githubusercontent.com/8919529/48808577-2738f200-ecd6-11e8-8bb1-32c1ec984907.png)

**Comment by emilioicai** [comment] 2018-11-21 07:34
@ahetawal-p I guess we need to modify `LottieAnimationViewManager.java` in `lottie-react-native`. Apparently CacheStrategy is not used anymore

**Comment by ahetawal-p** [comment] 2018-11-21 19:03
@emilioicai If the fix is the to just remove `CacheStrategy` let me try submit a PR for it, since it was only used for Android anyways.

**Comment by emilioicai** [comment] 2018-11-22 09:51
@ahetawal-p that would be great :) I'm looking forward to that PR

**Comment by emilioicai** [comment] 2018-11-26 12:56
@7ynk3r apparently updating to lottie-android 2.5.6 is useful and easy so I will update this repo to use that version

**Comment by emilioicai** [comment] 2018-11-26 12:58
Thanks @MaxToyberman ! I will update this repo with your suggested changes

**Comment by MaxToyberman** [comment] 2018-11-26 13:57
@emilioicai  Thanks !

**Comment by mlazari** [comment] 2018-12-04 11:40
@emilioicai For me the app still crashes when using master:
`"lottie-react-native": "https://github.com/react-community/lottie-react-native.git#13aa84aa2b1836034cef53c250866eba634e6b65",`
I did clean the project from Android Studio and rebuilt-it after changing `package.json` and running `npm i`.

**Comment by dphaener** [comment] 2018-12-04 16:37
@emilioicai Indeed it still crashes on master with Android SDK v28.0.0. It works fine on your master branch with Android SDK v27.0.0. We would love to get our project back on the newest Android SDK, so I hope this issue is fixed soon.

**Comment by emilioicai** [comment] 2018-12-04 16:44
oh! so the problem is Android SDK v28.0.0 

now I know how to reproduce so I will give it a try.

**Comment by schumannd** [comment] 2019-01-17 14:51
Any update on this issue? Should I downgrade my Android SDK to 27? I only noticed this error through a Google Play pre-launch report, so no clue how often or under which circumstances this error actually occurs.

**Comment by dphaener** [comment] 2019-01-17 19:43
@schumannd It seems to happen only on specific animations. I haven't done enough diving into the animations to see what causes some of them to crash, but I can definitely confirm that some animations work fine on the 28 SDK, and some do not. We are playing it safe and staying with 27 until this is resolved.

**Comment by emilioicai** [comment] 2019-01-18 08:02
@schumannd we are working to migrate to `lottie-android` 3.0 atm which should hopefully get rid of these issues

**Comment by amid67** [comment] 2019-01-18 10:35
I got this issue on some animation on android P
target sdk 28.0.0
lottie version 2.5.4

**Comment by iagorm** [comment] 2019-04-12 20:43
Any update about this, the crash still happens!

**Comment by emilioicai** [comment] 2019-04-15 07:51
@iagorm there's a PR waiting to be merged to fix this issue but it has some issues. @7ynk3r would you have some time to review it together?

**Comment by 7ynk3r** [comment] 2019-04-16 17:55
@emilioicai sure, anyday 6 pst works for me

**Comment by greg7gkb** [comment] 2019-05-10 00:56
What is preventing us from migrating to Lottie 3.0.0 at this point? Wondering if anyone has an existing PR for that.

Our app crashes with this issue at runtime with the most up-to-date dependencies:
* RN 0.59.8
* Android SDK/build tools 28
* lottie-react-native 2.6.1
* device running Android P

**Comment by emilioicai** [comment] 2019-05-10 07:46
@greg7gkb I keep getting several errors when trying to migrate to Lottie 3.0.0 myself. Did you manage to succeed on it? If so, could you send a PR?

**Comment by greg7gkb** [comment] 2019-05-13 17:23
Working on it: https://github.com/greg7gkb/lottie-react-native/commits/master
I've gone through about 10 rounds of build whack-a-mole but not solved yet.

**Comment by emilioicai** [comment] 2019-05-14 12:34
@greg7gkb it looks like you are making good progress. Let me know if I can help you in any way

**Comment by tlenclos** [comment] 2019-05-22 14:30
Specifying the version 2.5.6 (which contains the fix) seems to solve the issue for me

```
    implementation project(':lottie-react-native')
    implementation 'com.airbnb.android:lottie:2.5.6'
```

**Closed** 2019-08-09 11:18 UTC
Labels: bug
