### ISSUE TITLE
App Crash on iOS with RN 0.62

### ISSUE THREAD

**Issue by CaM2091** [react-native-community/lottie-react-native#638] opened 2020-04-24 10:17 UTC
### Description
App with Lottie animations crash for certain files on iOS with RN 0.62.2 (Error : `unrecognized selector sent to instance 0x60000048ec30`)
(Everything works well with older versions of RN on any version of Android/iOS)

### Steps to Reproduce

1. Create new project with `npx react-native init LottieTestApp`
2. `yarn add lottie-react-native`
`yarn add lottie-ios@3.1.3`
`cd ios`
`pod install`
3. Add this animation in project : https://gist.githubusercontent.com/CaM2091/c3251e262255520b99cf7221363ccac6/raw/8a2ecc9f8c4829216f715e49a8a7f09d91bddc63/my-animation.json
(Animation was generated with latest version of Bodymovin (5.6.5). I tried with version 5.5.8, same issue)
4. `import LottieView from 'lottie-react-native';`
`<LottieView source={require('./my-animation.json')} autoPlay />`

**Expected behavior:** For the lottie view animation to show

**Actual behavior:** App crash with this error in xCode : 

![image](https://user-images.githubusercontent.com/6414269/80201751-dfce3800-8624-11ea-8958-284812a3f467.png)

![Enregistrement de l’écran 2020-04-24 à 12 50 17 (2)](https://user-images.githubusercontent.com/6414269/80206102-0e9bdc80-862c-11ea-841d-556b77cbf06c.gif)

```
2020-04-24 13:24:14.423697+0200 LottieTestApp[78081:3565018] libMobileGestalt MobileGestalt.c:890: MGIsDeviceOneOfType is not supported on this platform.
2020-04-24 13:24:14.925586+0200 LottieTestApp[78081:3565018] [AXMediaCommon] Unable to look up screen scale
2020-04-24 13:24:14.925690+0200 LottieTestApp[78081:3565018] [AXMediaCommon] Unexpected physical screen orientation
2020-04-24 13:24:14.974087+0200 LottieTestApp[78081:3565018] [AXMediaCommon] Unable to look up screen scale
2020-04-24 13:24:14.980130+0200 LottieTestApp[78081:3565018] [AXMediaCommon] Unable to look up screen scale
2020-04-24 13:24:14.980223+0200 LottieTestApp[78081:3565018] [AXMediaCommon] Unexpected physical screen orientation
flipper: FlipperClient::addPlugin Inspector
flipper: FlipperClient::addPlugin Preferences
flipper: FlipperClient::addPlugin React
flipper: FlipperClient::addPlugin Network
2020-04-24 13:24:15.859 [info][tid:main][RCTRootView.m:294] Running application LottieTestApp ({
    initialProps =     {
    };
    rootTag = 1;
})
2020-04-24 13:24:17.063008+0200 LottieTestApp[78081:3565178] [] nw_socket_handle_socket_event [C5.1:1] Socket SO_ERROR [61: Connection refused]
2020-04-24 13:24:17.070516+0200 LottieTestApp[78081:3565178] [] nw_socket_handle_socket_event [C5.2:1] Socket SO_ERROR [61: Connection refused]
2020-04-24 13:24:17.074820+0200 LottieTestApp[78081:3565182] [] nw_connection_get_connected_socket [C5] Client called nw_connection_get_connected_socket on unconnected nw_connection
2020-04-24 13:24:17.075805+0200 LottieTestApp[78081:3565182] TCP Conn 0x600003394c00 Failed : error 0:61 [61]
2020-04-24 13:24:17.194 [info][tid:com.facebook.react.JavaScript] Running "LottieTestApp" with {"rootTag":1,"initialProps":{}}
2020-04-24 13:24:17.349359+0200 LottieTestApp[78081:3565179] -[NSURLResponse allHeaderFields]: unrecognized selector sent to instance 0x60000048ec30
2020-04-24 13:24:17.405622+0200 LottieTestApp[78081:3565179] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSURLResponse allHeaderFields]: unrecognized selector sent to instance 0x60000048ec30'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010872e1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000107cc8735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010874cf44 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000108732ed6 ___forwarding___ + 1446
	4   CoreFoundation                      0x0000000108734da8 _CF_forwarding_prep_0 + 120
	5   LottieTestApp                       0x0000000102195cdc +[SKResponseInfo shouldStripReponseBodyWithResponse:] + 76
	6   LottieTestApp                       0x0000000102195bb1 -[SKResponseInfo initWithIndentifier:timestamp:response:data:] + 241
	7   LottieTestApp                       0x000000010216f989 __71-[FLEXNetworkRecorder recordLoadingFinishedWithRequestID:responseBody:]_block_invoke + 825
	8   libdispatch.dylib                   0x0000000109f29595 _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x0000000109f2a602 _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x0000000109f31b0b _dispatch_lane_serial_drain + 791
	11  libdispatch.dylib                   0x0000000109f32784 _dispatch_lane_invoke + 428
	12  libdispatch.dylib                   0x0000000109f3c89a _dispatch_workloop_worker_thread + 733
	13  libsystem_pthread.dylib             0x000000010a322a3d _pthread_wqthread + 290
	14  libsystem_pthread.dylib             0x000000010a321b77 start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

### Versions

```
{
  LottieTestApp: '0.0.1',
  npm: '6.13.4',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.9.3',
  icu: '64.2',
  llhttp: '2.0.4',
  modules: '72',
  napi: '5',
  nghttp2: '1.40.0',
  node: '12.16.1',
  openssl: '1.1.1d',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.34.0',
  v8: '7.8.279.23-node.31',
  zlib: '1.2.11'
}
```

```
{
  "dependencies": {
    "lottie-ios": "3.1.3",
    "lottie-react-native": "^3.3.2",
    "react": "16.11.0",
    "react-native": "0.62.2"
  }
}
```
![image](https://user-images.githubusercontent.com/6414269/80203158-00978d00-8627-11ea-93b7-824c8b042ff1.png)

### Note
For example, it's working with this animation : https://gist.githubusercontent.com/CaM2091/7b6ab7666f9ebbd679f02511f4411751/raw/1361304dc13431399d9ea024000c62a6fcdc9ef9/my-working-animation.json

![Enregistrement de l’écran 2020-04-24 à 12 59 14](https://user-images.githubusercontent.com/6414269/80205868-ad740900-862b-11ea-8ce9-10190aa94188.gif)

**Comment by LLesage** [comment] 2020-04-24 11:31
Same issue here

**Comment by LLesage** [comment] 2020-05-06 12:34
12 days without any response?

**Comment by emilioicai** [comment] 2020-05-08 17:45
this looks like an issue with `lottie-ios`. Did you manage to find any related issue in https://github.com/airbnb/lottie-ios

**Comment by orhanoksuzz** [comment] 2020-05-12 12:39
you may get an error caused by the json format file you use. surprisingly when i work on some json files i get error on others

**Comment by NickMandylas** [comment] 2020-05-15 07:59
Getting same issue, upgraded to 0.62.2, only certain lottie files though..

**Comment by NickMandylas** [comment] 2020-05-16 08:18
Looking more closely, the error is only occurring with animation files that have had their images rasterized & encoded into the JSON file.

i.e. `"p":"data:image/png;base64,iVBORw ...`

**Comment by NickMandylas** [comment] 2020-05-16 09:04
Okay, found the actual cause of the issue. It's unrelated to lottie-react-native & lottie-ios.

Issue is with Flipper version 0.33.1, when an image source is a base64 string.
https://github.com/facebook/react-native/issues/28469.

**Comment by emilioicai** [comment] 2020-05-20 16:50
closing this as it looks it's not related to Lottie

**Closed by emilioicai** 2020-05-20 16:50 UTC
