### ISSUE TITLE
Callbacks for when animation has finished rendering?

### ISSUE THREAD

**Issue by SnoCat8** [react-native-community/lottie-react-native#315] opened 2018-04-04 23:32 UTC
I have my animation rendering correctly in my React Native Android App.  However, I want to close it once the animation finishes.  But it just sits there on the last frame.  Is there some sort of callback to determine the animation has finished? 

```
componentDidMount() {
        this.animation.play();
 render() {
        return (
                <View>
                    <Animation
                        ref={animation => {
                            this.animation = animation;
                        }}
                        loop={false}
                        source="Test.json"
                        imageAssetsFolder="images"
                    />
                </View>
        );
    }
```

**Comment by emilioicai** [comment] 2018-04-16 08:08
Unfortunately there is no `onFinished` method in React Native's Lottie API. You can use React Native's `Animated` API to control when the animation has ended as it is show in `LottieAnimatedExample.js`: 

https://github.com/airbnb/lottie-react-native/blob/b932a2af98c2dfe22484e8c0e22bbc2ab551e4c9/example/js/LottieAnimatedExample.js#L74

**Comment by li-yuan2** [comment] 2018-12-06 05:49
I have sent a pull request #415 to add onAnimationFinish callback function, which I think can fix this issue. @emilioicai

**Comment by SeanJoseph** [comment] 2018-12-18 05:06
@li-yuan2 tried using onAnimationFinish callback function, but it seems to be firing when the animation starts.  I think it is an issue with isCancelled, but I'm not familiar enough with the native code to be certain.

**Comment by li-yuan2** [comment] 2018-12-18 07:48
@SeanJoseph I can't reproduce it in ios simulator or my android physical device. Why do you think it's an issue with isCancelled? Do you have any hint?

**Comment by SeanJoseph** [comment] 2018-12-18 15:34
@li-yuan2 
`import React from 'react';
import LottieView from 'lottie-react-native';

export default class LottieContainer extends React.Component {
  constructor(props){
    super(props);
  }

  render() {
    return (
      <LottieView
        source={require('../assets/animations/blueGiftBox.json')}
        autoPlay = {true}
        loop = {false}
        onAnimationFinish = {this.props.navigation.navigate('Login')}
      />
    )
  }
}`

**Comment by emilioicai** [comment] 2018-12-18 15:38
change this:
`onAnimationFinish = {this.props.navigation.navigate('Login')}`

into this:
`onAnimationFinish = {() => this.props.navigation.navigate('Login')}`

The way you have it now calls the navigate method on every render instead of passing a callback

**Comment by emilioicai** [comment] 2018-12-18 15:39
I'm closing this issue as @li-yuan2 PR has been merged into master now and should be out with the next release of `lottie-react-native`

**Closed by emilioicai** 2018-12-18 15:39 UTC

**Comment by SeanJoseph** [comment] 2018-12-18 15:43
Whenever I run this code, the app starts on the Login screen and I get the following warning:
> Warning: Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern but can be moved to `componentWillMount`.

@emilioicai - I tried using an arrow function originally but it wasn't navigating after the animation was completed. (Note: I am not sure if it matters here, but I am using EXPO)

**Comment by emilioicai** [comment] 2018-12-18 15:45
hmm, which version of lottie-react-native are you using?

**Comment by SeanJoseph** [comment] 2018-12-18 15:48
"lottie-react-native": "^2.5.10"

**Comment by emilioicai** [comment] 2018-12-18 15:50
that's the issue :) `onAnimationFinish` has been merged to master but there has been no npm released. I will do it during this week. Sorry for the confusion. In the meantime you can use master on your `package.json`

**Comment by SeanJoseph** [comment] 2018-12-18 15:56
Haha, thank you @emilioicai. I really appreciate the quick response.

btw - @li-yuan2 this feature is awesome! 👍🏾👍🏾👍🏾

**Comment by ManuelAlanis** [comment] 2019-03-01 19:08
I am using `Animated` like this: 

The callback is inside the `start()` parameter with an `arrow function`

```
Animated.timing(this.state.xValue, {
            toValue: footerHeightPosition,
            duration: MILLISECOND_ANIMATION_DURATION,
            asing: Easing.back(),
        }).start(() => {
            //
            this.youCallbackFunc();
        });
```

**Comment by tjdcks12** [comment] 2020-08-18 13:08
`onAnimationFinish`
it doesn't work on
```json
 "lottie-ios": "^3.1.8",
 "lottie-react-native": "^3.5.0",
```

**Comment by ahmetabdi** [comment] 2020-08-27 21:17
> `onAnimationFinish`
> it doesn't work on
> 
> ```json
> "lottie-ios": "^3.1.8",
> "lottie-react-native": "^3.5.0",
> ```

Check docs it has your answer:

>A callback function which will be called when animation is finished. Note that this callback will be called only when loop is set to false.

**Comment by Alonew0lfxx** [comment] 2021-09-06 14:14
onAnimationFinish did worked when I changed `loop` prop to false
